let data = [
  {
    id: '17EF84121B8F41FC9C5D9C5E049E0956',
    dataSource: '',
    description: '国内进港航班',
    singleData: false,
    exampleData: [
      {
        id: '34402694',
        flightid: '2298095',
        linkedflightid: null,
        flighttask: 'W/Z',
        carrier: 'MF',
        flight: '8262',
        destination: 'XMN',
        direction: 'A',
        scheduledeparttime: '2017-11-20 16:30:00',
        estimatedeparttime: null,
        actualdeparttime: null,
        schedulearrivetime: '2017-11-20 19:00:00',
        estimatearrivetime: null,
        actualarrivetime: null,
        flightstatus: null,
        irregularstatus: null,
        flightnature: 'D',
        terminal: 'T3',
        shareflight: 'CZ5184/NS8262',
        route: 'XIC-CKG'
      },
      {
        id: '34402695',
        flightid: '2298095',
        linkedflightid: null,
        flighttask: 'W/Z',
        carrier: 'MF',
        flight: '8262',
        destination: 'XMN',
        direction: 'A',
        scheduledeparttime: '2017-11-20 16:30:00',
        estimatedeparttime: null,
        actualdeparttime: null,
        schedulearrivetime: '2017-11-20 19:00:00',
        estimatearrivetime: null,
        actualarrivetime: null,
        flightstatus: null,
        irregularstatus: null,
        flightnature: 'D',
        terminal: 'T3',
        shareflight: 'CZ5184/NS8262',
        route: 'XIC-CKG'
      },
      {
        id: '34402696',
        flightid: '2298095',
        linkedflightid: null,
        flighttask: 'W/Z',
        carrier: 'MF',
        flight: '8262',
        destination: 'XMN',
        direction: 'A',
        scheduledeparttime: '2017-11-20 16:30:00',
        estimatedeparttime: null,
        actualdeparttime: null,
        schedulearrivetime: '2017-11-20 19:00:00',
        estimatearrivetime: null,
        actualarrivetime: null,
        flightstatus: null,
        irregularstatus: null,
        flightnature: 'D',
        terminal: 'T3',
        shareflight: 'CZ5184/NS8262',
        route: 'XIC-CKG'
      },
      {
        id: '34402696',
        flightid: '2298095',
        linkedflightid: null,
        flighttask: 'W/Z',
        carrier: 'MF',
        flight: '8262',
        destination: 'XMN',
        direction: 'A',
        scheduledeparttime: '2017-11-20 16:30:00',
        estimatedeparttime: null,
        actualdeparttime: null,
        schedulearrivetime: '2017-11-20 19:00:00',
        estimatearrivetime: null,
        actualarrivetime: null,
        flightstatus: null,
        irregularstatus: null,
        flightnature: 'D',
        terminal: 'T3',
        shareflight: 'CZ5184/NS8262',
        route: 'XIC-CKG'
      },
      {
        id: '34402696',
        flightid: '2298095',
        linkedflightid: null,
        flighttask: 'W/Z',
        carrier: 'MF',
        flight: '8262',
        destination: 'XMN',
        direction: 'A',
        scheduledeparttime: '2017-11-20 16:30:00',
        estimatedeparttime: null,
        actualdeparttime: null,
        schedulearrivetime: '2017-11-20 19:00:00',
        estimatearrivetime: null,
        actualarrivetime: null,
        flightstatus: null,
        irregularstatus: null,
        flightnature: 'D',
        terminal: 'T3',
        shareflight: 'CZ5184/NS8262',
        route: 'XIC-CKG'
      },
      {
        id: '34402696',
        flightid: '2298095',
        linkedflightid: null,
        flighttask: 'W/Z',
        carrier: 'MF',
        flight: '8262',
        destination: 'XMN',
        direction: 'A',
        scheduledeparttime: '2017-11-20 16:30:00',
        estimatedeparttime: null,
        actualdeparttime: null,
        schedulearrivetime: '2017-11-20 19:00:00',
        estimatearrivetime: null,
        actualarrivetime: null,
        flightstatus: null,
        irregularstatus: null,
        flightnature: 'D',
        terminal: 'T3',
        shareflight: 'CZ5184/NS8262',
        route: 'XIC-CKG'
      },
      {
        id: '34402696',
        flightid: '2298095',
        linkedflightid: null,
        flighttask: 'W/Z',
        carrier: 'MF',
        flight: '8262',
        destination: 'XMN',
        direction: 'A',
        scheduledeparttime: '2017-11-20 16:30:00',
        estimatedeparttime: null,
        actualdeparttime: null,
        schedulearrivetime: '2017-11-20 19:00:00',
        estimatearrivetime: null,
        actualarrivetime: null,
        flightstatus: null,
        irregularstatus: null,
        flightnature: 'D',
        terminal: 'T3',
        shareflight: 'CZ5184/NS8262',
        route: 'XIC-CKG'
      }
    ]
  },
  {
    id: '5907A40F85EC4A1A9362E7BB2802BAC5',
    dataSource: '',
    description: '登机口',
    singleData: false,
    exampleData: [
      {
        id: '34402694',
        flightid: '2298095',
        linkedflightid: null,
        flighttask: 'W/Z',
        carrier: 'MF',
        flight: '8262',
        destination: 'XMN',
        direction: 'A',
        scheduledeparttime: '2017-11-20 16:30:00',
        estimatedeparttime: null,
        actualdeparttime: null,
        schedulearrivetime: '2017-11-20 19:00:00',
        estimatearrivetime: null,
        actualarrivetime: null,
        flightstatus: null,
        irregularstatus: null,
        flightnature: 'D',
        terminal: 'T3',
        shareflight: 'CZ5184/NS8262',
        route: 'XIC-CKG'
      }
    ]
  }
]

export default data
